# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Discrete_Coexpnet <- function(children, parents, c_names, p_names, nthreads, identical) {
    .Call('_DiffXCoExpNet_Discrete_Coexpnet', PACKAGE = 'DiffXCoExpNet', children, parents, c_names, p_names, nthreads, identical)
}

Coexpnet <- function(children, parents, c_names, p_names, k, nthreads, identical) {
    .Call('_DiffXCoExpNet_Coexpnet', PACKAGE = 'DiffXCoExpNet', children, parents, c_names, p_names, k, nthreads, identical)
}

Discrete_DiffCoexpnet <- function(exp_matr, n_conditions, conditions, indices, g_names, g_levels, nthreads) {
    .Call('_DiffXCoExpNet_Discrete_DiffCoexpnet', PACKAGE = 'DiffXCoExpNet', exp_matr, n_conditions, conditions, indices, g_names, g_levels, nthreads)
}

DiffCoexpnet <- function(exp_matr, n_conditions, conditions, indices, g_names, k, nthreads) {
    .Call('_DiffXCoExpNet_DiffCoexpnet', PACKAGE = 'DiffXCoExpNet', exp_matr, n_conditions, conditions, indices, g_names, k, nthreads)
}

tableRcpp <- function(x, y, xlevels = -1L, ylevels = -1L) {
    .Call('_DiffXCoExpNet_tableRcpp', PACKAGE = 'DiffXCoExpNet', x, y, xlevels, ylevels)
}

SharmaSongTestRcpp <- function(tables, nrows, ncols) {
    .Call('_DiffXCoExpNet_SharmaSongTestRcpp', PACKAGE = 'DiffXCoExpNet', tables, nrows, ncols)
}

